import "tailwindcss/tailwind.css";

import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import type { NextPage } from "next";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>HoldMyBudget</title>
        <meta name="description" content="Generated by create next app" />{" "}
      </Head>{" "}
      <main className="font-mono text-black">
        <h1 className="font-black font-mono text-center bg-gray-300 py-5">
          <Link href="/">
            <a className="text-black">🪣 HoldMyBudget</a>
          </Link>
        </h1>
        <div className="bg-green-50 p-5 flex justify-center content-center flex-col text-center">
          <h1>$5044.00</h1>

          <p>Total spends in January</p>
        </div>
        <div className="p-4 flex justify-center">
          <button className="bg-black text-white px-4 py-2">Add new</button>
        </div>
        <div className="px-5 py-10 ">
          <h1 className="font-black mb-5">Last transactions</h1>
          <div className="py-4 px-0">
            [<span className="text-green-500">income</span>/others] - New
            project payment - $100 - June 2, 2022
          </div>
          <div className="py-4 px-0">
            [<span className="text-red-500">expense</span>/utilities] - Internet
            bill - $10 - June 2, 2022
          </div>
        </div>
      </main>
      <footer className="text-center border-t-2 py-5">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          HoldMyBudget &copy; 2021
        </a>
      </footer>
    </>
  );
};

export default Home;
